# Generated by Django 4.2.7 on 2023-12-04 20:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'agent',
                'verbose_name_plural': 'agents',
            },
        ),
        migrations.CreateModel(
            name='InsuranceStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=63, unique=True)),
                ('description', models.TextField()),
                ('price', models.FloatField()),
                ('coverage', models.FloatField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2023, 12, 4, 20, 30, 25, 683513, tzinfo=datetime.timezone.utc), editable=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurance.insurancestatus')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance', to='insurance.insurancetype')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=31)),
                ('passport_number', models.CharField(max_length=31)),
                ('address', models.CharField(max_length=255)),
                ('birth_date', models.DateField()),
                ('profession', models.CharField(max_length=63)),
                ('income', models.IntegerField()),
                ('sex', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('weight', models.FloatField()),
                ('illness', models.CharField(max_length=255)),
                ('bad_habits', models.CharField(max_length=255)),
                ('surgeries', models.CharField(max_length=255)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='insurance.agent')),
            ],
            options={
                'verbose_name': 'client',
                'verbose_name_plural': 'clients',
            },
        ),
    ]
