# Generated by Django 4.2.7 on 2023-12-03 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="insurance",
            name="number",
            field=models.CharField(default="NONE", max_length=9, unique=True),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 17, 57, 25, 370496, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
