# Generated by Django 4.2.7 on 2023-12-03 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0002_insurance_number_alter_insurance_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 17, 58, 9, 5517, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.AlterField(
            model_name="insurance",
            name="number",
            field=models.CharField(max_length=9, unique=True),
        ),
    ]
