# Generated by Django 4.2.7 on 2023-12-03 17:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0003_alter_insurance_created_at_alter_insurance_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 3, 17, 58, 50, 729899, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
