# Generated by Django 4.2.7 on 2023-12-04 11:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0004_alter_insurance_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 4, 11, 0, 52, 122102, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
