# Generated by Django 4.2.7 on 2023-12-04 11:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("insurance", "0005_alter_insurance_created_at_delete_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="insurance",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 12, 4, 11, 1, 22, 400785, tzinfo=datetime.timezone.utc
                ),
                editable=False,
            ),
        ),
    ]
